In [3]:
import numpy as np # np는 별칭임

data = [0,1,2,3,4,5]
a1 = np.array(data) # 리스트를 넘파이 배열로 생성
print(a1)
print( type(a1) )

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
data2 = [0,1,2,3,0.5,3.14]
a2 = np.array(data2)
#정수와 실수가 섞여있으면 전부 실수로 변환
print( a2 )

[0.   1.   2.   3.   0.5  3.14]


In [9]:
x = np.array([0.1, 0.2, 0.3])
print( x.shape ) # 배열 구조를 리턴
print( x.dtype ) # 배열요소들의 타입을 리턴

(3,)
float64


In [13]:
y = np.array( ([1,2,3,], [4,5,6]) )
print(y.shape)
print(y.dtype)

(2, 3)
int64


In [17]:
a3 = np.arange(1, 10)
print(a3)
print( type(a3) )

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [19]:
a4 = np.arange(1, 10, 2)
print(a4)

[1 3 5 7 9]


In [23]:
a5 = np.arange(12).reshape(4, 3)
print( a5 )
print( a5.shape )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [28]:
# 개수지정해서 배열 만들기
a6 = np.linspace(1, 10, 10)
print(a6)
a6 = np.linspace(1, 10, 5) 
print(a6)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
a7 = np.linspace(0, np.pi, 20)
print(a7)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [32]:
a8 = np.zeros(10)
print( a8 )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
a9 = np.zeros( (3,4) )
print(a9)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
a10 = np.ones(5)
print(a10)

[1. 1. 1. 1. 1.]


In [36]:
a11 = np.ones( (3,2) )
print(a11)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
a12 = np.eye(5)
print(a12)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
a13 = np.array(['1.5', '3.14', '3', '12'])
print(a13)
print(a13.dtype)

['1.5' '3.14' '3' '12']
<U4


In [42]:
num_a13 = a13.astype(float)
print(num_a13)
print(num_a13.dtype)

[ 1.5   3.14  3.   12.  ]
float64


In [45]:
a14 = np.array(['1','2','3','4'])
int_a14 = a14.astype(int)
print(int_a14)

[1 2 3 4]


In [46]:
a15 = np.random.rand(2, 3)
print(a15) # 난수 생성

[[0.29265878 0.84344131 0.46406348]
 [0.18485846 0.80372073 0.56216752]]


In [47]:
a17 = np.random.randint(10, size=(3,4)) # 칸 수 지정
print(a17)

[[4 4 7 5]
 [2 7 0 1]
 [3 7 8 9]]


In [49]:
list1 = [1,2,3]
list2 = [3,5,6]
list3 = list1 + list2
print(list3)

[1, 2, 3, 3, 5, 6]


In [50]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [51]:
result = arr1 * arr2
print(result)

[ 4 10 18]


In [54]:
result = list1 * 3 # list 는 리스트 자체가 * 3 이 되고
print(result)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [55]:
result = arr1 * 3 # index 배열은 배열안에 값이 * 3 된다
print(result)

[3 6 9]


In [57]:
result = (arr1 >= 2 ) # 논리연산도 가능함
print(result)

[False  True  True]


In [58]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [59]:
print( arr.sum() ) # 합계
print( arr.mean() ) # 평균
print( arr.max() ) # 최대값
print( arr.min() ) # 최소값
print( arr.std() ) # 표준편차
print( arr.var() ) # 분산

10
2.0
4
0
1.4142135623730951
2.0


In [61]:
# 인덱싱
arr = np.array([1,2,3,4,5,6,])
print(arr[2])
print(arr[-1])

3
6


In [64]:
# 슬라이싱
print(arr[2:4])
print(arr[:3])
print(arr[3:])

[3 4]
[1 2 3]
[4 5 6]


In [69]:
# 행렬 연산
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[4,5], [6,8]])
# 행렬 합
result = np.add(m1, m2) # m1 + m2
print(result)
# 행렬 뺄셈
result = np.subtract( m1, m2 )
print(result)
# 행렬 곱 
result = np.dot(m1, m2)
print(result)

[[ 5  7]
 [ 9 12]]
[[-3 -3]
 [-3 -4]]
[[16 21]
 [36 47]]


In [74]:
arr = np.array([8,3,6,1,5])
print(np.sort(arr)) # 정렬
print(np.argsort(arr)) # 정렬된 원래 인덱스번호

print(np.argmin(arr)) # 값이 제일 낮은 인덱스번호
print(np.argmax(arr)) # 값이 제일 높은 인덱스번호

[1 3 5 6 8]
[3 1 4 2 0]
3
0


In [ ]:
# 브로드캐스팅 
# 배열간 크기가 다른 경우에도 연산을 해주는 기능
# 각 배열의 shape를 비교
# 뒤에서 차원 비교를 수행 -> 차원이 같거나 하나가 1이면 호환
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a.shape)
print(b.shape)

c = a + b
print(c)
print(c.shape)

(3,)
(3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]
(3, 3)
