In [ ]:
# Series : 라벨이 있는 1차원 데이터
import pandas as pd # 별칠은 pd로 

# 시리즈에는 시쿼스 데이터가 들어감 (1차원 데이터가 들어감)
# 리스트, 튜플가능한데 보통 리스트를 많이 사용함 
s1 = pd.Series( [10, 20, 30, 40, 50,] )
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [5]:
print(s1.index) # 인덱스 목록
print(s1.values) # 인덱스 값 목록

RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]


In [8]:
s2 = pd.Series(['a',1,'b',2,'c',3])
print(s2)

0    a
1    1
2    b
3    2
4    c
5    3
dtype: object


In [10]:
import numpy as np
s3 = pd.Series([10, np.nan, 30])
print(s3)

0    10.0
1     NaN
2    30.0
dtype: float64


In [14]:
index = ['2025-03-03', '1997-01-11', '2003-06-10']
s4 = pd.Series([100, 200, 300], index=index)
print(s4)

2025-03-03    100
1997-01-11    200
2003-06-10    300
dtype: int64


In [15]:
s5 = pd.Series({'국어' : 100, '영어' : 90, '수학' : 90})
print(s5)

국어    100
영어     90
수학     90
dtype: int64


In [20]:
# 데이터 프레임 ( 2차원 ) 행과 열이 존재
# 인덱스, 열, 값 이 존재함
index = ['하나', '둘', '셋']
columns = ['A','B','C']
values = [ [1,2,3,], [4,5,6,], [7,8,9]]

df = pd.DataFrame(values, index=index, columns=columns)
print(df)
print( df.index ) # 인덱스 목록
print( df.columns ) # 컬럼 목록
print( df.values ) # 값 목록

    A  B  C
하나  1  2  3
둘   4  5  6
셋   7  8  9
Index(['하나', '둘', '셋'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
data = {
  '학번' : ['1000', '1001', '1002'],
  '이름' : ['홍길동', '고길동', '유재석'],
  '점수' : [90, 70, 100]
}
df = pd.DataFrame(data)
print(df)

     학번   이름   점수
0  1000  홍길동   90
1  1001  고길동   70
2  1002  유재석  100


In [23]:
print( df.dtypes )


학번    object
이름    object
점수     int64
dtype: object


In [24]:
# 행렬 뒤집기
print( df.T )

       0     1     2
학번  1000  1001  1002
이름   홍길동   고길동   유재석
점수    90    70   100


In [25]:
df.index = ['A','B','C']
df

학번   이름   점수
A  1000  홍길동   90
B  1001  고길동   70
C  1002  유재석  100

In [27]:
df['이름'] # 원하는 컬럼 명을 이용해서 가져올 수 있음
print(type(df['이름']))

<class 'pandas.core.series.Series'>


In [32]:
df[['이름', '점수']]

이름   점수
A  홍길동   90
B  고길동   70
C  유재석  100

In [34]:
df.rename( columns={'이름' : 'name'}) # rename을 통해서 컬럼 이름도 변경이 가능함 

학번 name   점수
A  1000  홍길동   90
B  1001  고길동   70
C  1002  유재석  100

In [ ]:
# inplace=True : 원본에 반영
df.rename(columns={'이름' : 'name'}, inplace=True)
df

학번 name   점수
A  1000  홍길동   90
B  1001  고길동   70
C  1002  유재석  100

In [37]:
df.head() # 앞부분 n개 보기 ( 기본값은 5 )

학번 name   점수
A  1000  홍길동   90
B  1001  고길동   70
C  1002  유재석  100

In [ ]:
df.head(1) # 인덱스 기준

학번 name  점수
A  1000  홍길동  90

In [ ]:
df.tail(2) # 뒤에서부터 보고싶을때는 tail() 사용

학번 name   점수
B  1001  고길동   70
C  1002  유재석  100